<?php
/**
 * @file
 * Allows saving of domain specific configuration through the UI.
 */

/**
 * Implements hook_preprocess_page().
 */
function domain_admin_ui_preprocess_page(&$variables) {
  $admin_context = \Drupal::service('router.admin_context');

  if ($admin_context->isAdminRoute()) {
    $form = \Drupal::formBuilder()->getForm('Drupal\domain_admin_ui\Form\SwitchForm');
    $variables['page']['content']['domain_admin_ui_switch'] = $form;
  }
}
